### ISSUE TITLE
Missing error message for 0 Balance

### ISSUE THREAD

**Issue by BrunoMarshall** [TechFlow-Space/Raffle-frontend#1]
I have tried the Raffle Game beta version with an account without balance and i was able to "try" buy tickects without an error message. Of course did not work, but is missing the error message.

Expected:
Error message: "not enough balance to buy tickets"

**Comment by TechFlowSpace** [comment]
This issue has been solved  with this commit. https://github.com/TechFlow-Space/Raffle-frontend/commit/7de594018f72eac9ec900d3670e268a407558079

Now the balance is checked before making the call to blockchain.
